
<div class="container">
        <div class="logo-holder">
                <a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ),
                        'default',true
                    );
                    ?>">Coupons</a>
        </div>
<ul class="nav-list">
	<li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ),
                        'default',true
                    );
                 ?>"
		title="Home">Home</a></li>

	



	<li><a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'who'),
                        'default',true
                    );
                 ?>"
		title="Il nostro profilo aziendale">Chi siamo</a></li>
	<li><a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'faq'),
                        'default',true
                    );
                 ?>"
		title="Le risposte a tutte le tue domande">Faq</a></li>
    <li><a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'signup'),
                        'default',true
                    );
                 ?>"
		title="Registrati">regstrati</a></li>
    <li><a


    <li><a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login'),
                        'default',true
                    );
                 ?>"
		title="Registrati">Login</a></li>

</ul>
</div>
