
<div class="container">
        <div class="logo-holder">
                <a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ),
                        'default',true
                    );
                    ?>">Coupons</a>
        </div>
<ul class="nav-list">
	<li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ),
                        'default',true
                    );
                 ?>"
		title="Home">Home</a></li>


    <li><a
		href="
                <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'edit'),
                        'default',true
                    );
                 ?>"
		title="Edit">edit</a></li>

    <li><a
		href="
                <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'logout'),
                        'default',true
                    );
                 ?>"
		title="Registrati">Logout</a></li>

</ul>
</div>
